export const MANDATORY_CHECKS = [
  'IDENTITY_KYC',
  'BANK_BENEFICIARY',
  'OWNERSHIP_EVIDENCE',
  'NAME_MATCH',
  'ADDRESS_BOUNDS',
  'PROPERTY_IDENTIFIER',
  'PRESENCE_CHALLENGE',
  'DUPLICATES_CLEARED',
  'CONTACT_VERIFIED',
  'EXPIRY_DATE',
];
