import { useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native';
import { apiClient } from '../src/lib/api-client';

export default function PaymentScreen() {
  const [listingId, setListingId] = useState(''); const [agreementId, setAgreementId] = useState(''); const [amount, setAmount] = useState('');
  const [result, setResult] = useState<any>(); const [history, setHistory] = useState<any[]>([]); const [loading, setLoading] = useState(false);
  async function check() { setLoading(true); try { setResult(await apiClient(`/payments/eligibility?listingId=${encodeURIComponent(listingId)}&agreementId=${encodeURIComponent(agreementId)}&amount=${Number(amount)}`)); } catch (e: any) { Alert.alert('Cannot check readiness', e.message); } finally { setLoading(false); } }
  async function checkout() { if (!result?.eligible) return; setLoading(true); try { const order = await apiClient('/payments/orders', { method: 'POST', headers: { 'idempotency-key': `mobile-${Date.now()}` }, body: JSON.stringify({ listingId, agreementId, amount: Number(amount) }) }); Alert.alert('Sandbox order created', `Test payment ${order.id}`); } catch (e: any) { Alert.alert('Payment blocked', e.message); } finally { setLoading(false); } }
  useEffect(() => { apiClient('/payments/history').then(setHistory).catch(() => undefined); }, []);
  return <SafeAreaView><ScrollView contentContainerStyle={{ padding: 24, gap: 14 }}><Text style={{ fontSize: 24, fontWeight: '700' }}>Test/Sandbox Payment</Text><Text>This checkout never charges real money.</Text><TextInput placeholder="Listing ID" value={listingId} onChangeText={setListingId} style={{ borderWidth: 1, padding: 12, borderRadius: 8 }} /><TextInput placeholder="Signed agreement ID" value={agreementId} onChangeText={setAgreementId} style={{ borderWidth: 1, padding: 12, borderRadius: 8 }} /><TextInput placeholder="Amount in whole paise" keyboardType="numeric" value={amount} onChangeText={setAmount} style={{ borderWidth: 1, padding: 12, borderRadius: 8 }} /><Pressable onPress={check} style={{ backgroundColor: '#334155', padding: 14, borderRadius: 8 }}><Text style={{ color: 'white', textAlign: 'center' }}>{loading ? 'Checking…' : 'Check payment readiness'}</Text></Pressable>{result && <View style={{ gap: 8 }}><Text style={{ fontWeight: '700' }}>{result.eligible ? 'Ready for sandbox checkout' : 'Payment disabled until requirements are met'}</Text>{result.items.map((item: any) => <Text key={item.code} style={{ color: item.passed ? '#15803d' : '#b91c1c' }}>{item.passed ? '✓' : '×'} {item.description}</Text>)}<Pressable disabled={!result.eligible} onPress={checkout} style={{ backgroundColor: result.eligible ? '#2563eb' : '#94a3b8', padding: 14, borderRadius: 8 }}><Text style={{ color: 'white', textAlign: 'center' }}>Create sandbox order</Text></Pressable></View>}<Text style={{ fontSize: 18, fontWeight: '700', marginTop: 16 }}>Payment history</Text>{history.map(item => <View key={item.id} style={{ borderWidth: 1, padding: 12, borderRadius: 8 }}><Text>TEST/SANDBOX PAYMENT · {item.status}</Text><Text>{item.amount} {item.currency}</Text></View>)}</ScrollView></SafeAreaView>;
}
