export const VERIFICATION_CHECK_TYPES = {
  REGISTRY_EXISTENCE: 'REGISTRY_EXISTENCE',
  OWNERSHIP_MATCH: 'OWNERSHIP_MATCH',
  DOCUMENT_AI: 'DOCUMENT_AI',
} as const;

export type VerificationCheckType =
  typeof VERIFICATION_CHECK_TYPES[keyof typeof VERIFICATION_CHECK_TYPES];
